/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVerbasCooperadasRouteImport } from './routes/_app.verbas-cooperadas'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppSellOutRouteImport } from './routes/_app.sell-out'
import { Route as AppRetornoAsLojasRouteImport } from './routes/_app.retorno-as-lojas'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProdutosEmFaltaRouteImport } from './routes/_app.produtos-em-falta'
import { Route as AppPontasDeGondolaRouteImport } from './routes/_app.pontas-de-gondola'
import { Route as AppFracionamentoRouteImport } from './routes/_app.fracionamento'
import { Route as AppFornecedoresRouteImport } from './routes/_app.fornecedores'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCentralProdutosEmFaltaRouteImport } from './routes/_app.central-produtos-em-falta'
import { Route as AppCatalogoDeProdutosRouteImport } from './routes/_app.catalogo-de-produtos'
import { Route as AppCampanhasEncerradasRouteImport } from './routes/_app.campanhas-encerradas'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'
import { Route as AppBancoDeOportunidadesRouteImport } from './routes/_app.banco-de-oportunidades'
import { Route as AppSellOutIndexRouteImport } from './routes/_app.sell-out.index'
import { Route as AppSellOutAcertosRouteImport } from './routes/_app.sell-out.acertos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerbasCooperadasRoute = AppVerbasCooperadasRouteImport.update({
  id: '/verbas-cooperadas',
  path: '/verbas-cooperadas',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSellOutRoute = AppSellOutRouteImport.update({
  id: '/sell-out',
  path: '/sell-out',
  getParentRoute: () => AppRoute,
} as any)
const AppRetornoAsLojasRoute = AppRetornoAsLojasRouteImport.update({
  id: '/retorno-as-lojas',
  path: '/retorno-as-lojas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosEmFaltaRoute = AppProdutosEmFaltaRouteImport.update({
  id: '/produtos-em-falta',
  path: '/produtos-em-falta',
  getParentRoute: () => AppRoute,
} as any)
const AppPontasDeGondolaRoute = AppPontasDeGondolaRouteImport.update({
  id: '/pontas-de-gondola',
  path: '/pontas-de-gondola',
  getParentRoute: () => AppRoute,
} as any)
const AppFracionamentoRoute = AppFracionamentoRouteImport.update({
  id: '/fracionamento',
  path: '/fracionamento',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCentralProdutosEmFaltaRoute =
  AppCentralProdutosEmFaltaRouteImport.update({
    id: '/central-produtos-em-falta',
    path: '/central-produtos-em-falta',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogoDeProdutosRoute = AppCatalogoDeProdutosRouteImport.update({
  id: '/catalogo-de-produtos',
  path: '/catalogo-de-produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasEncerradasRoute = AppCampanhasEncerradasRouteImport.update({
  id: '/campanhas-encerradas',
  path: '/campanhas-encerradas',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppBancoDeOportunidadesRoute = AppBancoDeOportunidadesRouteImport.update({
  id: '/banco-de-oportunidades',
  path: '/banco-de-oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppSellOutIndexRoute = AppSellOutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSellOutRoute,
} as any)
const AppSellOutAcertosRoute = AppSellOutAcertosRouteImport.update({
  id: '/acertos',
  path: '/acertos',
  getParentRoute: () => AppSellOutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/banco-de-oportunidades': typeof AppBancoDeOportunidadesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/campanhas-encerradas': typeof AppCampanhasEncerradasRoute
  '/catalogo-de-produtos': typeof AppCatalogoDeProdutosRoute
  '/central-produtos-em-falta': typeof AppCentralProdutosEmFaltaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/fracionamento': typeof AppFracionamentoRoute
  '/pontas-de-gondola': typeof AppPontasDeGondolaRoute
  '/produtos-em-falta': typeof AppProdutosEmFaltaRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/retorno-as-lojas': typeof AppRetornoAsLojasRoute
  '/sell-out': typeof AppSellOutRouteWithChildren
  '/usuarios': typeof AppUsuariosRoute
  '/verbas-cooperadas': typeof AppVerbasCooperadasRoute
  '/sell-out/acertos': typeof AppSellOutAcertosRoute
  '/sell-out/': typeof AppSellOutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/banco-de-oportunidades': typeof AppBancoDeOportunidadesRoute
  '/campanhas': typeof AppCampanhasRoute
  '/campanhas-encerradas': typeof AppCampanhasEncerradasRoute
  '/catalogo-de-produtos': typeof AppCatalogoDeProdutosRoute
  '/central-produtos-em-falta': typeof AppCentralProdutosEmFaltaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/fracionamento': typeof AppFracionamentoRoute
  '/pontas-de-gondola': typeof AppPontasDeGondolaRoute
  '/produtos-em-falta': typeof AppProdutosEmFaltaRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/retorno-as-lojas': typeof AppRetornoAsLojasRoute
  '/usuarios': typeof AppUsuariosRoute
  '/verbas-cooperadas': typeof AppVerbasCooperadasRoute
  '/sell-out/acertos': typeof AppSellOutAcertosRoute
  '/sell-out': typeof AppSellOutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/banco-de-oportunidades': typeof AppBancoDeOportunidadesRoute
  '/_app/campanhas': typeof AppCampanhasRoute
  '/_app/campanhas-encerradas': typeof AppCampanhasEncerradasRoute
  '/_app/catalogo-de-produtos': typeof AppCatalogoDeProdutosRoute
  '/_app/central-produtos-em-falta': typeof AppCentralProdutosEmFaltaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fornecedores': typeof AppFornecedoresRoute
  '/_app/fracionamento': typeof AppFracionamentoRoute
  '/_app/pontas-de-gondola': typeof AppPontasDeGondolaRoute
  '/_app/produtos-em-falta': typeof AppProdutosEmFaltaRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/retorno-as-lojas': typeof AppRetornoAsLojasRoute
  '/_app/sell-out': typeof AppSellOutRouteWithChildren
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/verbas-cooperadas': typeof AppVerbasCooperadasRoute
  '/_app/sell-out/acertos': typeof AppSellOutAcertosRoute
  '/_app/sell-out/': typeof AppSellOutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/banco-de-oportunidades'
    | '/campanhas'
    | '/campanhas-encerradas'
    | '/catalogo-de-produtos'
    | '/central-produtos-em-falta'
    | '/configuracoes'
    | '/dashboard'
    | '/fornecedores'
    | '/fracionamento'
    | '/pontas-de-gondola'
    | '/produtos-em-falta'
    | '/relatorios'
    | '/retorno-as-lojas'
    | '/sell-out'
    | '/usuarios'
    | '/verbas-cooperadas'
    | '/sell-out/acertos'
    | '/sell-out/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/banco-de-oportunidades'
    | '/campanhas'
    | '/campanhas-encerradas'
    | '/catalogo-de-produtos'
    | '/central-produtos-em-falta'
    | '/configuracoes'
    | '/dashboard'
    | '/fornecedores'
    | '/fracionamento'
    | '/pontas-de-gondola'
    | '/produtos-em-falta'
    | '/relatorios'
    | '/retorno-as-lojas'
    | '/usuarios'
    | '/verbas-cooperadas'
    | '/sell-out/acertos'
    | '/sell-out'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/banco-de-oportunidades'
    | '/_app/campanhas'
    | '/_app/campanhas-encerradas'
    | '/_app/catalogo-de-produtos'
    | '/_app/central-produtos-em-falta'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/fornecedores'
    | '/_app/fracionamento'
    | '/_app/pontas-de-gondola'
    | '/_app/produtos-em-falta'
    | '/_app/relatorios'
    | '/_app/retorno-as-lojas'
    | '/_app/sell-out'
    | '/_app/usuarios'
    | '/_app/verbas-cooperadas'
    | '/_app/sell-out/acertos'
    | '/_app/sell-out/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verbas-cooperadas': {
      id: '/_app/verbas-cooperadas'
      path: '/verbas-cooperadas'
      fullPath: '/verbas-cooperadas'
      preLoaderRoute: typeof AppVerbasCooperadasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sell-out': {
      id: '/_app/sell-out'
      path: '/sell-out'
      fullPath: '/sell-out'
      preLoaderRoute: typeof AppSellOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retorno-as-lojas': {
      id: '/_app/retorno-as-lojas'
      path: '/retorno-as-lojas'
      fullPath: '/retorno-as-lojas'
      preLoaderRoute: typeof AppRetornoAsLojasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos-em-falta': {
      id: '/_app/produtos-em-falta'
      path: '/produtos-em-falta'
      fullPath: '/produtos-em-falta'
      preLoaderRoute: typeof AppProdutosEmFaltaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pontas-de-gondola': {
      id: '/_app/pontas-de-gondola'
      path: '/pontas-de-gondola'
      fullPath: '/pontas-de-gondola'
      preLoaderRoute: typeof AppPontasDeGondolaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fracionamento': {
      id: '/_app/fracionamento'
      path: '/fracionamento'
      fullPath: '/fracionamento'
      preLoaderRoute: typeof AppFracionamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/central-produtos-em-falta': {
      id: '/_app/central-produtos-em-falta'
      path: '/central-produtos-em-falta'
      fullPath: '/central-produtos-em-falta'
      preLoaderRoute: typeof AppCentralProdutosEmFaltaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo-de-produtos': {
      id: '/_app/catalogo-de-produtos'
      path: '/catalogo-de-produtos'
      fullPath: '/catalogo-de-produtos'
      preLoaderRoute: typeof AppCatalogoDeProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas-encerradas': {
      id: '/_app/campanhas-encerradas'
      path: '/campanhas-encerradas'
      fullPath: '/campanhas-encerradas'
      preLoaderRoute: typeof AppCampanhasEncerradasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banco-de-oportunidades': {
      id: '/_app/banco-de-oportunidades'
      path: '/banco-de-oportunidades'
      fullPath: '/banco-de-oportunidades'
      preLoaderRoute: typeof AppBancoDeOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sell-out/': {
      id: '/_app/sell-out/'
      path: '/'
      fullPath: '/sell-out/'
      preLoaderRoute: typeof AppSellOutIndexRouteImport
      parentRoute: typeof AppSellOutRoute
    }
    '/_app/sell-out/acertos': {
      id: '/_app/sell-out/acertos'
      path: '/acertos'
      fullPath: '/sell-out/acertos'
      preLoaderRoute: typeof AppSellOutAcertosRouteImport
      parentRoute: typeof AppSellOutRoute
    }
  }
}

interface AppSellOutRouteChildren {
  AppSellOutAcertosRoute: typeof AppSellOutAcertosRoute
  AppSellOutIndexRoute: typeof AppSellOutIndexRoute
}

const AppSellOutRouteChildren: AppSellOutRouteChildren = {
  AppSellOutAcertosRoute: AppSellOutAcertosRoute,
  AppSellOutIndexRoute: AppSellOutIndexRoute,
}

const AppSellOutRouteWithChildren = AppSellOutRoute._addFileChildren(
  AppSellOutRouteChildren,
)

interface AppRouteChildren {
  AppBancoDeOportunidadesRoute: typeof AppBancoDeOportunidadesRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppCampanhasEncerradasRoute: typeof AppCampanhasEncerradasRoute
  AppCatalogoDeProdutosRoute: typeof AppCatalogoDeProdutosRoute
  AppCentralProdutosEmFaltaRoute: typeof AppCentralProdutosEmFaltaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppFracionamentoRoute: typeof AppFracionamentoRoute
  AppPontasDeGondolaRoute: typeof AppPontasDeGondolaRoute
  AppProdutosEmFaltaRoute: typeof AppProdutosEmFaltaRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRetornoAsLojasRoute: typeof AppRetornoAsLojasRoute
  AppSellOutRoute: typeof AppSellOutRouteWithChildren
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVerbasCooperadasRoute: typeof AppVerbasCooperadasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBancoDeOportunidadesRoute: AppBancoDeOportunidadesRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppCampanhasEncerradasRoute: AppCampanhasEncerradasRoute,
  AppCatalogoDeProdutosRoute: AppCatalogoDeProdutosRoute,
  AppCentralProdutosEmFaltaRoute: AppCentralProdutosEmFaltaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppFracionamentoRoute: AppFracionamentoRoute,
  AppPontasDeGondolaRoute: AppPontasDeGondolaRoute,
  AppProdutosEmFaltaRoute: AppProdutosEmFaltaRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRetornoAsLojasRoute: AppRetornoAsLojasRoute,
  AppSellOutRoute: AppSellOutRouteWithChildren,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVerbasCooperadasRoute: AppVerbasCooperadasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
